# Generated by Django 3.2.5 on 2021-07-14 09:04

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Programming', 'Programming'), ('Web Apps', 'Web Apps'), ('Designs', 'Designs'), ('Cyber Security', 'Cyber Security')], default='Web Apps', max_length=120)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('about', models.CharField(max_length=500)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('github', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.category')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'App',
            },
        ),
    ]
