# Generated by Django 3.2.4 on 2021-07-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Web Apps', 'Web Apps'), ('Designs', 'Designs'), ('Cyber Security', 'Cyber Security')], default='Web Apps', max_length=120),
        ),
    ]
