# Generated by Django 3.2.4 on 2021-07-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210702_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
