# Generated by Django 3.1.7 on 2021-04-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20210403_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='Date_uplaoded',
            new_name='Date_uploaded',
        ),
    ]
