# Generated by Django 3.1.7 on 2021-04-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Artist', models.CharField(max_length=200)),
                ('File', models.FileField(upload_to='media/video')),
                ('Album', models.CharField(max_length=50)),
                ('Date_uplaoded', models.DateTimeField(auto_now_add=True)),
                ('Info', models.CharField(max_length=500)),
            ],
        ),
    ]
