# Generated by Django 3.1.7 on 2021-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='File',
            field=models.FileField(upload_to='video'),
        ),
    ]
