# Generated by Django 3.1.7 on 2021-04-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210403_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Date_uplaoded',
            new_name='Date_uploaded',
        ),
        migrations.RemoveField(
            model_name='video',
            name='Album',
        ),
        migrations.RemoveField(
            model_name='video',
            name='Artist',
        ),
    ]
