# Generated by Django 3.1.7 on 2021-04-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20210409_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Image',
            field=models.FileField(null=True, upload_to='images/video'),
        ),
    ]
